### ISSUE TITLE
Hosts

### ISSUE THREAD

**Issue by denrusvrn** [henrikwidlund/HostsParser#13]
Greetings!
We kindly ask you: could you upload the hosts file here and update it from time to time, as it was previously with you initially! Thank you in advance and thank you for your understanding!

**Comment by henrikwidlund** [comment]
Hi,

Congratulations on creating the first issue :)
Sorry about moving the file without updating readme, it is now available here: https://henrikwidlund.github.io/HostsParser/hosts
It was moved to the GH Pages of the repository to avoid committing to the main branch each time it's built. I'll update the readme.

**Comment by henrikwidlund** [comment]
Fixed, thanks for reporting!
