### ISSUE TITLE
Hosts.I welcome you!

### ISSUE THREAD

**Issue by denrusvrn** [henrikwidlund/hostsparser#92]
### Feature or Problem

I welcome you! I have a suggestion for you, namely, the fact is that I used StevenBlack hosts before and there seemed to be no problems, since the list could be selected and I took the minimum Unified hosts = (adware + malware) all the time, which is located here on this ades https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts or http://sbc.io/hosts/hosts. 

### Proposed Solution

And so I decided to suggest changing the source to the optimal one, or it would be cool and cool if you made all the lists to choose from, it's just that you have to add to the white list and it is constantly growing, and it's not very convenient for all this.

### Alternative Solutions

https://github.com/StevenBlack/hosts/tree/master/alternates

### Additional Context

https://github.com/StevenBlack/hosts/tree/master/extensions

**Comment by henrikwidlund** [comment]
Hi, thanks for the feedback. Just so I understand your suggestion, you'd like the ability to specify multiple sources for the hosts based file?

**Comment by denrusvrn** [comment]
I welcome you once again!
Yes, almost so, but in a slightly different way, namely that there is a choice of lists as it is implemented in stevenblack hosts, but adapted for adguard home, in general, so that there is a choice of lists before using, choose one more suitable.
Is it even possible to implement that there was a selection of the hosts list before adding it and using it?
Thank you in advance and thank you for your understanding!

**Comment by henrikwidlund** [comment]
@denrusvrn I've created a pull request with what I think would address your feature request, please have a look. Let me know if you need binaries and I'll publish a pre-release.

**Comment by denrusvrn** [comment]
Greetings!I wanted to see and use your ready-made and adapted Hosts file for and for Adguard Home with a choice of the optimal one, as implemented by Steven Black, that is, you should eventually have several ready-made hosts files for selection and use in Adguard Home, since you have only one ready-made file for use, and I would like several, as they say, to have a choice for use, for example, I always use this list Unified hosts = (adware + malware) all the time, which are here on this https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts or http://sbc.io/hosts/hosts and if necessary I add something else separately for example from these lists https://github.com/StevenBlack/hosts/tree/master/alternates and https://github.com/StevenBlack/hosts/tree/master/extensions.So I ask you to do the same if possible, namely, so that you also have a lot of updated hosts lists to decide and choose a more suitable one.Thank you in advance and thank you for your understanding!

**Comment by henrikwidlund** [comment]
@denrusvrn I understand what you're after. The pr linked to this issue will enable you to create whatever combination you want, but you'd need to host it on your own. Is this something you can do? Let me know if this isn't a solution that works for you and we'll see what can be done.

**Comment by denrusvrn** [comment]
Here you have a link to the default filter is Steven Black/ghosts with fake news, gambling and porn extensions here at this address or link https://henrikwidlund.github.io/hostsparser/filter.txt And that's why I'm asking if you could do the minimum by default, this is how Unified hosts = (adware + malware), which is located here https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts or http://sbc.io/hosts/hosts. Or make several ready-made lists for use in adguard home, that is, so that it would be like this: 
https://henrikwidlund.github.io/hostsparser/filter.tx is Unified hosts = (adware + malware), 
https://henrikwidlund.github.io/hostsparser/filter_1.tx is Unified hosts + fakenews + gambling + porn, 
https://henrikwidlund.github.io/hostsparser/filter_2.tx is Unified hosts + fakenews + gambling + social, 
https://henrikwidlund.github.io/hostsparser/filter_3.tx is Unified hosts + fakenews + gambling + porn + social, 
etc and so on and so forth, so that it is possible to immediately use ready-made links to ready-made lists of your hosts converted from steven black for adguard home???

**Comment by henrikwidlund** [comment]
@denrusvrn I've now adjusted so that four different filters are created and hosted, let me know if you're happy with it, and I'll close the issue.

**Comment by denrusvrn** [comment]
Thank you!
You are the best!!!

**Comment by henrikwidlund** [comment]
No problem! Closing the issue :)
